import { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { articlesApi } from 'api/client';
import { SITE_NAME } from 'brand';
import Container from 'components/common/Container/Container';
import styles from './Articles.module.css';

export default function ArticleDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [article, setArticle] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchArticle = async () => {
      try {
        const { article: data } = await articlesApi.get(id);
        setArticle(data);
        document.title = `${data.title} · ${SITE_NAME}`;
      } catch (err) {
        if (err.status === 404) {
          navigate('/not-found', { replace: true });
        } else {
          setError('Failed to load the article.');
        }
      } finally {
        setLoading(false);
      }
    };

    fetchArticle();
  }, [id, navigate]);

  if (loading) return <Container className={styles.detailContainer}>Loading article...</Container>;
  if (error) return <Container className={styles.detailContainer} style={{ color: 'red' }}>{error}</Container>;
  if (!article) return null;

  return (
    <Container className={styles.detailContainer} style={{ display: 'block' }}>
      <Link to="/articles" className={styles.backBtn}>
        ← Back to Articles
      </Link>

      {article.cover_image && (
        <img src={article.cover_image} alt="" className={styles.detailImage} />
      )}

      <header className={styles.detailHeader}>
        <h1 className={styles.detailTitle}>{article.title}</h1>
        <div className={styles.detailMeta}>
          <span className={styles.author}>By {article.author}</span>
          <span className={styles.date}>{new Date(article.published_date).toLocaleDateString()}</span>
        </div>
      </header>

      {/* Renders the HTML generated by React Quill */}
      <div 
        className={styles.contentHtml} 
        dangerouslySetInnerHTML={{ __html: article.content_html }} 
      />
    </Container>
  );
}
